name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Debug, Release ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v9
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgArtifactIgnoreEntries: '!vcpkg_installed/**/share/**'
          vcpkgGitCommitId: '9b3bd80'
          appendedCacheKey: ${{ matrix.os }}-${{ matrix.build_type }}

      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build

      - name: Test
        run: cmake --build build --target test

      - name: Package
        run: cmake --install build --prefix install --component Runtime --strip --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.build_type }}
          path: install
