name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Debug, Release ]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'e2ca0145eda96cb8b2f972d9ff4b7bd1619fefa0'
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: false

      - name: Build, Test and Package
        shell: pwsh
        run: ${{ github.workspace }}/scripts/build_test_and_package-for_remote.ps1 -os '${{ matrix.os }}' -build_type '${{ matrix.build_type }}'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.build_type }}
          path: install
