name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        build_type: [ Debug, Release ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'e2ca0145eda96cb8b2f972d9ff4b7bd1619fefa0'
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: false
          appendedCacheKey: ${{ matrix.os }}-${{ matrix.build_type }}

      - name: Check Dir
        shell: bash
        run: tree -L 2

      - name: check vcpkg dir for vcpkg.cmake
        shell: bash
        run: tree -L 2 '${{ github.workspace }}/vcpkg/scripts/'

      - name: Configure
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

      - name: Build
        run: cmake --build build

      - name: Test
        run: cmake --build build --target test

      - name: Package
        run: cmake --install build --prefix install --component Runtime --strip --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os }}-${{ matrix.build_type }}
          path: install
