name: Build, Test, Package and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: github.event_name != 'pull_request' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        build_type: [ Release ]

    outputs:
      release_version: ${{ steps.get_release_version.outputs.value }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Release Version
        id: get_release_version
        shell: pwsh
        run: |
          $json_content = Get-Content -Path './vcpkg.json' -Raw | ConvertFrom-Json
          echo "VALUE=v$($json_content.'version-string')" >> "$GITHUB_OUTPUT"

      - name: ECHO Version
        run: echo "The Version is ${{ steps.get_release_version.outputs.VALUE }}"
