name: Build, Test, Package and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: github.event_name != 'pull_request' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        build_type: [ Release ]

    outputs:
      release_version: ${{ steps.get_release_version.outputs.value }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: 'e2ca0145eda96cb8b2f972d9ff4b7bd1619fefa0'
          vcpkgJsonGlob: '**/vcpkg.json'
          runVcpkgInstall: false

      - name: Set up CMake, Ninja, and required tools
        shell: pwsh
        run: |
          if ("${{ runner.os }}" -eq "Linux") {
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build
          } elseif ("${{ runner.os }}" -eq "Windows") {
            choco install -y cmake ninja nsis
          } else {
            return 1
          }

      - name: Build, Test and Package
        shell: pwsh
        run: |
          Invoke-Expression "./scripts/build_test_and_package.ps1 -OS ${{ runner.os }} -BuildType ${{ matrix.build_type }}" -OutVariable path_to_package
          Write-Host "OUTPUT_PACKAGE: $(./scripts/pack_to_single_file.ps1 -DirPath $path_to_package -CompressedFileNameIfRequired ${{ matrix.os }}_${{ matrix.build_type }})"
          "path_to_installers=$path_to_package" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Get Release Version
        id: get_release_version
        shell: pwsh
        run: |
          $version = "v$((Get-Content -Path './vcpkg.json' -Raw | ConvertFrom-Json).'version-string')"
          Write-Host "version-string: $version"
          "current_release_version=$version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append

      - name: List Installer files
        run: |
          echo "Release Version: v${{ env.current_release_version }}"
          tree -L 3 '${{ env.path_to_installers }}'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: all
          path: ${{ steps.package_build.outputs.dir }}/*

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || (github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Verify artifacts
        run: tree -L 3 ./artifacts

      - name: Set Release Tag ID
        run: |
          echo "current_release_tag_id=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "current_release_version=v${{ needs.build.outputs.release_version }}" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ env.current_release_tag_id }}
          release_name: Release ${{ env.current_release_version }}
          draft: false
          prerelease: false

      - name: Upload Artifacts to Release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          cd artifacts/all
          for file in *; do
            echo "Uploading $file"
            gh release upload ${{ steps.create_tag.outputs.id }} "$file" --clobber
          done
